-- phpMyAdmin SQL Dump
-- Generated by exportDatabases.js
-- Generation Time: 2025-11-15 08:07:31
--
-- Database: `keohams`
--

SET SQL_MODE = "NO_AUTO_VALUE_ON_ZERO";
START TRANSACTION;
SET time_zone = "+00:00";

/*!40101 SET @OLD_CHARACTER_SET_CLIENT=@@CHARACTER_SET_CLIENT */;
/*!40101 SET @OLD_CHARACTER_SET_RESULTS=@@CHARACTER_SET_RESULTS */;
/*!40101 SET @OLD_COLLATION_CONNECTION=@@COLLATION_CONNECTION */;
/*!40101 SET NAMES utf8mb4 */;


-- --------------------------------------------------------

--
-- Table structure for table `activity_logs`
--

DROP TABLE IF EXISTS `activity_logs`;
CREATE TABLE `activity_logs` (
  `id` int(10) unsigned NOT NULL AUTO_INCREMENT,
  `user_id` int(10) unsigned DEFAULT NULL,
  `user_type` enum('ADMIN','USER','AFFILIATE') NOT NULL,
  `action` varchar(100) NOT NULL,
  `entity_type` varchar(50) DEFAULT NULL,
  `entity_id` int(10) unsigned DEFAULT NULL,
  `description` text DEFAULT NULL,
  `metadata` longtext CHARACTER SET utf8mb4 COLLATE utf8mb4_bin DEFAULT NULL CHECK (json_valid(`metadata`)),
  `ip_address` varchar(45) DEFAULT NULL,
  `user_agent` varchar(255) DEFAULT NULL,
  `created_at` timestamp NOT NULL DEFAULT current_timestamp(),
  PRIMARY KEY (`id`),
  KEY `activity_logs_user_id_index` (`user_id`),
  KEY `activity_logs_user_type_index` (`user_type`),
  KEY `activity_logs_action_index` (`action`),
  KEY `activity_logs_entity_type_index` (`entity_type`),
  KEY `activity_logs_created_at_index` (`created_at`),
  CONSTRAINT `activity_logs_user_id_foreign` FOREIGN KEY (`user_id`) REFERENCES `users` (`id`) ON DELETE SET NULL
) ENGINE=InnoDB AUTO_INCREMENT=8 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;

-- --------------------------------------------------------

--
-- Table structure for table `admin_audit_events`
--

DROP TABLE IF EXISTS `admin_audit_events`;
CREATE TABLE `admin_audit_events` (
  `id` int(10) unsigned NOT NULL AUTO_INCREMENT,
  `admin_id` int(10) unsigned NOT NULL,
  `target_user_id` int(10) unsigned DEFAULT NULL,
  `action` varchar(255) NOT NULL,
  `metadata` longtext CHARACTER SET utf8mb4 COLLATE utf8mb4_bin DEFAULT NULL CHECK (json_valid(`metadata`)),
  `created_at` datetime NOT NULL DEFAULT current_timestamp(),
  PRIMARY KEY (`id`)
) ENGINE=InnoDB AUTO_INCREMENT=14 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;

-- --------------------------------------------------------

--
-- Table structure for table `affiliates`
--

DROP TABLE IF EXISTS `affiliates`;
CREATE TABLE `affiliates` (
  `id` int(10) unsigned NOT NULL AUTO_INCREMENT,
  `user_id` int(10) unsigned DEFAULT NULL,
  `email` varchar(255) DEFAULT NULL,
  `password_hash` varchar(255) DEFAULT NULL,
  `name` varchar(255) DEFAULT NULL,
  `phone` varchar(255) DEFAULT NULL,
  `email_verified` tinyint(1) DEFAULT 0,
  `token_version` int(11) DEFAULT 1,
  `is_active_account` tinyint(1) DEFAULT 1,
  `email_verified_at` timestamp NULL DEFAULT NULL,
  `deleted_at` timestamp NULL DEFAULT NULL,
  `referral_code` varchar(20) NOT NULL COMMENT 'Unique referral code for the affiliate',
  `parent_affiliate_id` int(10) unsigned DEFAULT NULL,
  `total_earnings` decimal(15,2) DEFAULT 0.00 COMMENT 'Total commissions earned',
  `available_balance` decimal(15,2) DEFAULT 0.00 COMMENT 'Available balance for withdrawal',
  `pending_balance` decimal(15,2) DEFAULT 0.00 COMMENT 'Pending commissions awaiting verification',
  `direct_referrals` int(11) DEFAULT 0 COMMENT 'Number of direct referrals',
  `total_downline` int(11) DEFAULT 0 COMMENT 'Total network size',
  `is_active` tinyint(1) DEFAULT 1,
  `created_at` timestamp NOT NULL DEFAULT current_timestamp(),
  `updated_at` timestamp NOT NULL DEFAULT current_timestamp(),
  PRIMARY KEY (`id`),
  UNIQUE KEY `affiliates_referral_code_unique` (`referral_code`),
  KEY `affiliates_user_id_index` (`user_id`),
  KEY `affiliates_parent_affiliate_id_index` (`parent_affiliate_id`),
  KEY `affiliates_referral_code_index` (`referral_code`),
  KEY `affiliates_is_active_created_at_index` (`is_active`,`created_at`),
  KEY `affiliates_email_index` (`email`),
  KEY `affiliates_is_active_account_index` (`is_active_account`),
  CONSTRAINT `affiliates_parent_affiliate_id_foreign` FOREIGN KEY (`parent_affiliate_id`) REFERENCES `affiliates` (`id`) ON DELETE SET NULL,
  CONSTRAINT `affiliates_user_id_foreign` FOREIGN KEY (`user_id`) REFERENCES `users` (`id`) ON DELETE CASCADE
) ENGINE=InnoDB AUTO_INCREMENT=3 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;

-- --------------------------------------------------------

--
-- Table structure for table `affiliate_sales`
--

DROP TABLE IF EXISTS `affiliate_sales`;
CREATE TABLE `affiliate_sales` (
  `id` int(10) unsigned NOT NULL AUTO_INCREMENT,
  `affiliate_id` int(10) unsigned NOT NULL,
  `customer_id` int(10) unsigned DEFAULT NULL,
  `sale_reference` varchar(255) NOT NULL COMMENT 'Unique reference for the sale',
  `sale_amount` decimal(15,2) NOT NULL COMMENT 'Total sale value',
  `payment_method` enum('ONLINE','BANK_TRANSFER','CASH','OTHER') NOT NULL,
  `payment_details` text DEFAULT NULL COMMENT 'Payment proof/details',
  `verification_status` enum('PENDING','VERIFIED','REJECTED') DEFAULT 'PENDING',
  `verified_by` int(10) unsigned DEFAULT NULL,
  `verified_at` timestamp NULL DEFAULT NULL,
  `verification_notes` text DEFAULT NULL,
  `commissions_paid` tinyint(1) DEFAULT 0 COMMENT 'Whether commissions have been distributed',
  `commissions_paid_at` timestamp NULL DEFAULT NULL,
  `created_at` timestamp NOT NULL DEFAULT current_timestamp(),
  `updated_at` timestamp NOT NULL DEFAULT current_timestamp(),
  PRIMARY KEY (`id`),
  UNIQUE KEY `affiliate_sales_sale_reference_unique` (`sale_reference`),
  KEY `affiliate_sales_verified_by_foreign` (`verified_by`),
  KEY `affiliate_sales_affiliate_id_index` (`affiliate_id`),
  KEY `affiliate_sales_customer_id_index` (`customer_id`),
  KEY `affiliate_sales_sale_reference_index` (`sale_reference`),
  KEY `affiliate_sales_verification_status_created_at_index` (`verification_status`,`created_at`),
  KEY `affiliate_sales_commissions_paid_verification_status_index` (`commissions_paid`,`verification_status`),
  CONSTRAINT `affiliate_sales_affiliate_id_foreign` FOREIGN KEY (`affiliate_id`) REFERENCES `affiliates` (`id`) ON DELETE CASCADE,
  CONSTRAINT `affiliate_sales_customer_id_foreign` FOREIGN KEY (`customer_id`) REFERENCES `users` (`id`) ON DELETE SET NULL,
  CONSTRAINT `affiliate_sales_verified_by_foreign` FOREIGN KEY (`verified_by`) REFERENCES `users` (`id`) ON DELETE SET NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;

-- --------------------------------------------------------

--
-- Table structure for table `affiliate_verification_tokens`
--

DROP TABLE IF EXISTS `affiliate_verification_tokens`;
CREATE TABLE `affiliate_verification_tokens` (
  `id` int(10) unsigned NOT NULL AUTO_INCREMENT,
  `affiliate_id` int(10) unsigned NOT NULL,
  `type` varchar(255) NOT NULL COMMENT 'verify-email, password-reset',
  `token` varchar(255) NOT NULL,
  `expires_at` timestamp NOT NULL DEFAULT current_timestamp() ON UPDATE current_timestamp(),
  `created_at` timestamp NOT NULL DEFAULT current_timestamp(),
  `updated_at` timestamp NOT NULL DEFAULT current_timestamp(),
  PRIMARY KEY (`id`),
  UNIQUE KEY `affiliate_verification_tokens_token_unique` (`token`),
  KEY `affiliate_verification_tokens_affiliate_id_index` (`affiliate_id`),
  KEY `affiliate_verification_tokens_token_index` (`token`),
  KEY `affiliate_verification_tokens_type_expires_at_index` (`type`,`expires_at`),
  CONSTRAINT `affiliate_verification_tokens_affiliate_id_foreign` FOREIGN KEY (`affiliate_id`) REFERENCES `affiliates` (`id`) ON DELETE CASCADE
) ENGINE=InnoDB AUTO_INCREMENT=3 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;

-- --------------------------------------------------------

--
-- Table structure for table `affiliate_withdrawals`
--

DROP TABLE IF EXISTS `affiliate_withdrawals`;
CREATE TABLE `affiliate_withdrawals` (
  `id` int(10) unsigned NOT NULL AUTO_INCREMENT,
  `affiliate_id` int(10) unsigned NOT NULL,
  `amount` decimal(15,2) NOT NULL,
  `method` enum('BANK_TRANSFER','PAYPAL','MOBILE_MONEY','CRYPTO') NOT NULL,
  `payment_details` longtext CHARACTER SET utf8mb4 COLLATE utf8mb4_bin NOT NULL COMMENT 'Bank account, PayPal email, etc.' CHECK (json_valid(`payment_details`)),
  `status` enum('PENDING','PROCESSING','COMPLETED','CANCELLED') DEFAULT 'PENDING',
  `processed_by` int(10) unsigned DEFAULT NULL,
  `processed_at` timestamp NULL DEFAULT NULL,
  `processing_notes` text DEFAULT NULL,
  `transaction_reference` varchar(255) DEFAULT NULL,
  `created_at` timestamp NOT NULL DEFAULT current_timestamp(),
  `updated_at` timestamp NOT NULL DEFAULT current_timestamp(),
  PRIMARY KEY (`id`),
  KEY `affiliate_withdrawals_processed_by_foreign` (`processed_by`),
  KEY `affiliate_withdrawals_affiliate_id_index` (`affiliate_id`),
  KEY `affiliate_withdrawals_status_created_at_index` (`status`,`created_at`),
  CONSTRAINT `affiliate_withdrawals_affiliate_id_foreign` FOREIGN KEY (`affiliate_id`) REFERENCES `affiliates` (`id`) ON DELETE CASCADE,
  CONSTRAINT `affiliate_withdrawals_processed_by_foreign` FOREIGN KEY (`processed_by`) REFERENCES `users` (`id`) ON DELETE SET NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;

-- --------------------------------------------------------

--
-- Table structure for table `bulk_discounts`
--

DROP TABLE IF EXISTS `bulk_discounts`;
CREATE TABLE `bulk_discounts` (
  `id` int(10) unsigned NOT NULL AUTO_INCREMENT,
  `product_id` int(10) unsigned NOT NULL,
  `min_qty` int(11) NOT NULL,
  `max_qty` int(11) DEFAULT NULL,
  `unit_price` decimal(12,2) NOT NULL,
  `created_at` timestamp NOT NULL DEFAULT current_timestamp(),
  `updated_at` timestamp NOT NULL DEFAULT current_timestamp(),
  PRIMARY KEY (`id`),
  KEY `bulk_discounts_product_id_foreign` (`product_id`),
  CONSTRAINT `bulk_discounts_product_id_foreign` FOREIGN KEY (`product_id`) REFERENCES `products` (`id`) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;

-- --------------------------------------------------------

--
-- Table structure for table `categories`
--

DROP TABLE IF EXISTS `categories`;
CREATE TABLE `categories` (
  `id` int(10) unsigned NOT NULL AUTO_INCREMENT,
  `name` varchar(255) NOT NULL,
  `parent_id` int(10) unsigned DEFAULT NULL,
  `created_at` timestamp NOT NULL DEFAULT current_timestamp(),
  `updated_at` timestamp NOT NULL DEFAULT current_timestamp(),
  PRIMARY KEY (`id`),
  KEY `categories_parent_id_foreign` (`parent_id`),
  CONSTRAINT `categories_parent_id_foreign` FOREIGN KEY (`parent_id`) REFERENCES `categories` (`id`) ON DELETE SET NULL
) ENGINE=InnoDB AUTO_INCREMENT=7 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;

-- --------------------------------------------------------

--
-- Table structure for table `chat_messages`
--

DROP TABLE IF EXISTS `chat_messages`;
CREATE TABLE `chat_messages` (
  `id` int(10) unsigned NOT NULL AUTO_INCREMENT,
  `thread_id` int(10) unsigned NOT NULL,
  `sender_id` int(10) unsigned NOT NULL,
  `body` text NOT NULL,
  `created_at` timestamp NOT NULL DEFAULT current_timestamp(),
  `seen_at` timestamp NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  KEY `chat_messages_thread_id_index` (`thread_id`),
  KEY `chat_messages_sender_id_index` (`sender_id`),
  KEY `chat_messages_thread_id_created_at_index` (`thread_id`,`created_at`),
  KEY `idx_chat_messages_thread_created` (`thread_id`,`created_at`),
  KEY `idx_chat_messages_sender_id` (`sender_id`),
  CONSTRAINT `chat_messages_sender_id_foreign` FOREIGN KEY (`sender_id`) REFERENCES `users` (`id`) ON DELETE CASCADE,
  CONSTRAINT `chat_messages_thread_id_foreign` FOREIGN KEY (`thread_id`) REFERENCES `chat_threads` (`id`) ON DELETE CASCADE
) ENGINE=InnoDB AUTO_INCREMENT=98 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;

-- --------------------------------------------------------

--
-- Table structure for table `chat_message_hides`
--

DROP TABLE IF EXISTS `chat_message_hides`;
CREATE TABLE `chat_message_hides` (
  `id` int(10) unsigned NOT NULL AUTO_INCREMENT,
  `message_id` int(10) unsigned NOT NULL,
  `user_id` int(10) unsigned NOT NULL,
  `hidden_at` timestamp NOT NULL DEFAULT current_timestamp(),
  PRIMARY KEY (`id`),
  UNIQUE KEY `chat_message_hides_message_id_user_id_unique` (`message_id`,`user_id`),
  KEY `chat_message_hides_message_id_index` (`message_id`),
  KEY `chat_message_hides_user_id_index` (`user_id`),
  CONSTRAINT `chat_message_hides_message_id_foreign` FOREIGN KEY (`message_id`) REFERENCES `chat_messages` (`id`) ON DELETE CASCADE,
  CONSTRAINT `chat_message_hides_user_id_foreign` FOREIGN KEY (`user_id`) REFERENCES `users` (`id`) ON DELETE CASCADE
) ENGINE=InnoDB AUTO_INCREMENT=20 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;

-- --------------------------------------------------------

--
-- Table structure for table `chat_threads`
--

DROP TABLE IF EXISTS `chat_threads`;
CREATE TABLE `chat_threads` (
  `id` int(10) unsigned NOT NULL AUTO_INCREMENT,
  `user_id` int(10) unsigned NOT NULL,
  `product_id` int(10) unsigned DEFAULT NULL,
  `subject` varchar(255) DEFAULT NULL,
  `created_by` int(10) unsigned NOT NULL,
  `created_at` timestamp NOT NULL DEFAULT current_timestamp(),
  PRIMARY KEY (`id`),
  UNIQUE KEY `chat_threads_user_id_product_id_unique` (`user_id`,`product_id`),
  KEY `chat_threads_user_id_index` (`user_id`),
  KEY `chat_threads_product_id_index` (`product_id`),
  KEY `chat_threads_created_by_foreign` (`created_by`),
  KEY `chat_threads_created_at_index` (`created_at`),
  CONSTRAINT `chat_threads_created_by_foreign` FOREIGN KEY (`created_by`) REFERENCES `users` (`id`) ON DELETE CASCADE,
  CONSTRAINT `chat_threads_product_id_foreign` FOREIGN KEY (`product_id`) REFERENCES `products` (`id`) ON DELETE SET NULL,
  CONSTRAINT `chat_threads_user_id_foreign` FOREIGN KEY (`user_id`) REFERENCES `users` (`id`) ON DELETE CASCADE
) ENGINE=InnoDB AUTO_INCREMENT=48 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;

-- --------------------------------------------------------

--
-- Table structure for table `chat_thread_hides`
--

DROP TABLE IF EXISTS `chat_thread_hides`;
CREATE TABLE `chat_thread_hides` (
  `id` int(10) unsigned NOT NULL AUTO_INCREMENT,
  `thread_id` int(10) unsigned NOT NULL,
  `user_id` int(10) unsigned NOT NULL,
  `hidden_at` timestamp NOT NULL DEFAULT current_timestamp(),
  PRIMARY KEY (`id`),
  UNIQUE KEY `chat_thread_hides_thread_id_user_id_unique` (`thread_id`,`user_id`),
  KEY `chat_thread_hides_thread_id_index` (`thread_id`),
  KEY `chat_thread_hides_user_id_index` (`user_id`),
  CONSTRAINT `chat_thread_hides_thread_id_foreign` FOREIGN KEY (`thread_id`) REFERENCES `chat_threads` (`id`) ON DELETE CASCADE,
  CONSTRAINT `chat_thread_hides_user_id_foreign` FOREIGN KEY (`user_id`) REFERENCES `users` (`id`) ON DELETE CASCADE
) ENGINE=InnoDB AUTO_INCREMENT=10 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;

-- --------------------------------------------------------

--
-- Table structure for table `commission_records`
--

DROP TABLE IF EXISTS `commission_records`;
CREATE TABLE `commission_records` (
  `id` int(10) unsigned NOT NULL AUTO_INCREMENT,
  `sale_id` int(10) unsigned NOT NULL,
  `affiliate_id` int(10) unsigned NOT NULL,
  `level` int(11) NOT NULL COMMENT '0 = direct seller, 1+ = upline levels',
  `commission_rate` decimal(5,2) NOT NULL COMMENT 'Commission percentage applied',
  `commission_amount` decimal(15,2) NOT NULL COMMENT 'Commission amount earned',
  `status` enum('PENDING','PAID','CANCELLED') DEFAULT 'PENDING',
  `paid_at` timestamp NULL DEFAULT NULL,
  `created_at` timestamp NOT NULL DEFAULT current_timestamp(),
  `updated_at` timestamp NOT NULL DEFAULT current_timestamp(),
  PRIMARY KEY (`id`),
  UNIQUE KEY `commission_records_sale_id_affiliate_id_level_unique` (`sale_id`,`affiliate_id`,`level`),
  KEY `commission_records_sale_id_index` (`sale_id`),
  KEY `commission_records_affiliate_id_index` (`affiliate_id`),
  KEY `commission_records_affiliate_id_status_index` (`affiliate_id`,`status`),
  KEY `commission_records_level_status_index` (`level`,`status`),
  CONSTRAINT `commission_records_affiliate_id_foreign` FOREIGN KEY (`affiliate_id`) REFERENCES `affiliates` (`id`) ON DELETE CASCADE,
  CONSTRAINT `commission_records_sale_id_foreign` FOREIGN KEY (`sale_id`) REFERENCES `affiliate_sales` (`id`) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;

-- --------------------------------------------------------

--
-- Table structure for table `commission_settings`
--

DROP TABLE IF EXISTS `commission_settings`;
CREATE TABLE `commission_settings` (
  `id` int(10) unsigned NOT NULL AUTO_INCREMENT,
  `level` int(11) NOT NULL COMMENT 'Commission level (0 = direct, 1+ = upline)',
  `rate` decimal(5,2) NOT NULL COMMENT 'Commission rate percentage',
  `max_total_rate` decimal(5,2) DEFAULT 25.00 COMMENT 'Maximum total commission percentage',
  `is_active` tinyint(1) DEFAULT 1,
  `created_at` timestamp NOT NULL DEFAULT current_timestamp(),
  `updated_at` timestamp NOT NULL DEFAULT current_timestamp(),
  PRIMARY KEY (`id`),
  UNIQUE KEY `commission_settings_level_unique` (`level`)
) ENGINE=InnoDB AUTO_INCREMENT=8 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;

-- --------------------------------------------------------

--
-- Table structure for table `contact_messages`
--

DROP TABLE IF EXISTS `contact_messages`;
CREATE TABLE `contact_messages` (
  `id` int(10) unsigned NOT NULL AUTO_INCREMENT,
  `user_id` int(10) unsigned DEFAULT NULL,
  `name` varchar(120) NOT NULL,
  `email` varchar(180) NOT NULL,
  `subject` varchar(180) NOT NULL,
  `body` text NOT NULL,
  `is_read` tinyint(1) NOT NULL DEFAULT 0,
  `created_at` timestamp NOT NULL DEFAULT current_timestamp(),
  PRIMARY KEY (`id`),
  KEY `contact_messages_user_id_foreign` (`user_id`),
  CONSTRAINT `contact_messages_user_id_foreign` FOREIGN KEY (`user_id`) REFERENCES `users` (`id`) ON DELETE SET NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;

-- --------------------------------------------------------

--
-- Table structure for table `email_2fa_codes`
--

DROP TABLE IF EXISTS `email_2fa_codes`;
CREATE TABLE `email_2fa_codes` (
  `id` int(10) unsigned NOT NULL AUTO_INCREMENT,
  `user_id` int(10) unsigned NOT NULL,
  `code` varchar(10) NOT NULL,
  `purpose` varchar(20) NOT NULL COMMENT 'login or verification',
  `used` tinyint(1) DEFAULT 0,
  `expires_at` timestamp NOT NULL DEFAULT current_timestamp() ON UPDATE current_timestamp(),
  `created_at` timestamp NOT NULL DEFAULT current_timestamp(),
  `updated_at` timestamp NOT NULL DEFAULT current_timestamp(),
  PRIMARY KEY (`id`),
  KEY `email_2fa_codes_user_id_code_index` (`user_id`,`code`),
  KEY `email_2fa_codes_expires_at_index` (`expires_at`),
  CONSTRAINT `email_2fa_codes_user_id_foreign` FOREIGN KEY (`user_id`) REFERENCES `users` (`id`) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;

-- --------------------------------------------------------

--
-- Table structure for table `knex_migrations`
--

DROP TABLE IF EXISTS `knex_migrations`;
CREATE TABLE `knex_migrations` (
  `id` int(10) unsigned NOT NULL AUTO_INCREMENT,
  `name` varchar(255) DEFAULT NULL,
  `batch` int(11) DEFAULT NULL,
  `migration_time` timestamp NOT NULL DEFAULT current_timestamp() ON UPDATE current_timestamp(),
  PRIMARY KEY (`id`)
) ENGINE=InnoDB AUTO_INCREMENT=38 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;

-- --------------------------------------------------------

--
-- Table structure for table `knex_migrations_lock`
--

DROP TABLE IF EXISTS `knex_migrations_lock`;
CREATE TABLE `knex_migrations_lock` (
  `index` int(10) unsigned NOT NULL AUTO_INCREMENT,
  `is_locked` int(11) DEFAULT NULL,
  PRIMARY KEY (`index`)
) ENGINE=InnoDB AUTO_INCREMENT=2 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;

-- --------------------------------------------------------

--
-- Table structure for table `kyc_audit_log`
--

DROP TABLE IF EXISTS `kyc_audit_log`;
CREATE TABLE `kyc_audit_log` (
  `id` int(10) unsigned NOT NULL AUTO_INCREMENT,
  `kyc_submission_id` int(10) unsigned NOT NULL,
  `user_id` int(10) unsigned NOT NULL,
  `admin_id` int(10) unsigned DEFAULT NULL,
  `action` enum('SUBMITTED','DOCUMENT_UPLOADED','OCR_PROCESSED','FACE_VERIFIED','ADMIN_REVIEWED','APPROVED','REJECTED','RESUBMIT_REQUESTED','DOCUMENT_EXPIRED','DATA_DELETED') NOT NULL,
  `status_before` enum('PENDING','UNDER_REVIEW','APPROVED','REJECTED','RESUBMIT_REQUIRED') DEFAULT NULL,
  `status_after` enum('PENDING','UNDER_REVIEW','APPROVED','REJECTED','RESUBMIT_REQUIRED') DEFAULT NULL,
  `remarks` text DEFAULT NULL,
  `metadata` longtext CHARACTER SET utf8mb4 COLLATE utf8mb4_bin DEFAULT NULL COMMENT 'Additional context like IP, device info' CHECK (json_valid(`metadata`)),
  `created_at` timestamp NOT NULL DEFAULT current_timestamp(),
  PRIMARY KEY (`id`),
  KEY `kyc_audit_log_kyc_submission_id_index` (`kyc_submission_id`),
  KEY `kyc_audit_log_user_id_index` (`user_id`),
  KEY `kyc_audit_log_admin_id_index` (`admin_id`),
  KEY `kyc_audit_log_action_index` (`action`),
  KEY `kyc_audit_log_created_at_index` (`created_at`),
  CONSTRAINT `kyc_audit_log_admin_id_foreign` FOREIGN KEY (`admin_id`) REFERENCES `users` (`id`) ON DELETE SET NULL,
  CONSTRAINT `kyc_audit_log_kyc_submission_id_foreign` FOREIGN KEY (`kyc_submission_id`) REFERENCES `kyc_submissions` (`id`) ON DELETE CASCADE,
  CONSTRAINT `kyc_audit_log_user_id_foreign` FOREIGN KEY (`user_id`) REFERENCES `users` (`id`) ON DELETE CASCADE
) ENGINE=InnoDB AUTO_INCREMENT=5 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;

-- --------------------------------------------------------

--
-- Table structure for table `kyc_face_matches`
--

DROP TABLE IF EXISTS `kyc_face_matches`;
CREATE TABLE `kyc_face_matches` (
  `id` int(10) unsigned NOT NULL AUTO_INCREMENT,
  `kyc_submission_id` int(10) unsigned NOT NULL,
  `id_face_path` varchar(500) DEFAULT NULL COMMENT 'Extracted face from ID',
  `selfie_face_path` varchar(500) DEFAULT NULL COMMENT 'Extracted face from live photo',
  `similarity_score` decimal(5,2) DEFAULT NULL,
  `face_landmarks` longtext CHARACTER SET utf8mb4 COLLATE utf8mb4_bin DEFAULT NULL COMMENT 'Detected facial landmarks' CHECK (json_valid(`face_landmarks`)),
  `liveness_passed` tinyint(1) DEFAULT 0,
  `liveness_checks` longtext CHARACTER SET utf8mb4 COLLATE utf8mb4_bin DEFAULT NULL COMMENT 'Liveness detection results' CHECK (json_valid(`liveness_checks`)),
  `match_status` enum('MATCHED','NOT_MATCHED','UNCERTAIN','ERROR') NOT NULL,
  `error_message` text DEFAULT NULL,
  `processed_at` timestamp NOT NULL DEFAULT current_timestamp(),
  PRIMARY KEY (`id`),
  KEY `kyc_face_matches_kyc_submission_id_index` (`kyc_submission_id`),
  KEY `kyc_face_matches_match_status_index` (`match_status`),
  CONSTRAINT `kyc_face_matches_kyc_submission_id_foreign` FOREIGN KEY (`kyc_submission_id`) REFERENCES `kyc_submissions` (`id`) ON DELETE CASCADE
) ENGINE=InnoDB AUTO_INCREMENT=2 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;

-- --------------------------------------------------------

--
-- Table structure for table `kyc_ocr_results`
--

DROP TABLE IF EXISTS `kyc_ocr_results`;
CREATE TABLE `kyc_ocr_results` (
  `id` int(10) unsigned NOT NULL AUTO_INCREMENT,
  `kyc_submission_id` int(10) unsigned NOT NULL,
  `document_type` enum('ID','ADDRESS_PROOF') NOT NULL,
  `extracted_text` longtext CHARACTER SET utf8mb4 COLLATE utf8mb4_bin DEFAULT NULL COMMENT 'Raw OCR text output' CHECK (json_valid(`extracted_text`)),
  `parsed_fields` longtext CHARACTER SET utf8mb4 COLLATE utf8mb4_bin DEFAULT NULL COMMENT 'Structured extracted fields' CHECK (json_valid(`parsed_fields`)),
  `confidence_score` decimal(5,2) DEFAULT NULL,
  `requires_manual_review` tinyint(1) DEFAULT 0,
  `manual_corrections` text DEFAULT NULL,
  `processed_at` timestamp NOT NULL DEFAULT current_timestamp(),
  PRIMARY KEY (`id`),
  KEY `kyc_ocr_results_kyc_submission_id_index` (`kyc_submission_id`),
  KEY `kyc_ocr_results_document_type_index` (`document_type`),
  CONSTRAINT `kyc_ocr_results_kyc_submission_id_foreign` FOREIGN KEY (`kyc_submission_id`) REFERENCES `kyc_submissions` (`id`) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;

-- --------------------------------------------------------

--
-- Table structure for table `kyc_submissions`
--

DROP TABLE IF EXISTS `kyc_submissions`;
CREATE TABLE `kyc_submissions` (
  `id` int(10) unsigned NOT NULL AUTO_INCREMENT,
  `user_id` int(10) unsigned NOT NULL,
  `status` enum('PENDING','APPROVED','REJECTED') NOT NULL DEFAULT 'PENDING',
  `type` varchar(255) NOT NULL DEFAULT 'ID',
  `files` longtext CHARACTER SET utf8mb4 COLLATE utf8mb4_bin DEFAULT NULL CHECK (json_valid(`files`)),
  `notes` text DEFAULT NULL,
  `reviewer_id` int(10) unsigned DEFAULT NULL,
  `review_notes` text DEFAULT NULL,
  `submitted_at` timestamp NOT NULL DEFAULT current_timestamp(),
  `reviewed_at` timestamp NULL DEFAULT NULL,
  `created_at` timestamp NOT NULL DEFAULT current_timestamp(),
  `updated_at` timestamp NOT NULL DEFAULT current_timestamp(),
  `doc_country` varchar(2) DEFAULT NULL,
  `doc_type` varchar(255) DEFAULT NULL,
  `doc_hash` varchar(255) DEFAULT NULL,
  `escalation_level` int(11) DEFAULT 0,
  `fail_reason_code` varchar(255) DEFAULT NULL,
  `risk_score_at_submission` int(11) DEFAULT NULL,
  `id_type` enum('NATIONAL_ID','DRIVERS_LICENSE','PASSPORT','OTHER') DEFAULT NULL,
  `id_number` varchar(100) DEFAULT NULL,
  `id_issue_date` date DEFAULT NULL,
  `id_expiry_date` date DEFAULT NULL,
  `id_document_path` varchar(500) DEFAULT NULL COMMENT 'Path to government ID image/PDF',
  `live_photo_path` varchar(500) DEFAULT NULL COMMENT 'Path to live selfie for face verification',
  `face_match_score` decimal(5,2) DEFAULT NULL COMMENT 'Face similarity score 0-100',
  `face_match_status` enum('PENDING','MATCHED','NOT_MATCHED','ERROR') DEFAULT 'PENDING',
  `liveness_check_passed` tinyint(1) DEFAULT NULL,
  `address_proof_type` enum('UTILITY_BILL','BANK_STATEMENT','RENTAL_AGREEMENT','OTHER') DEFAULT NULL,
  `address_proof_path` varchar(500) DEFAULT NULL,
  `address_proof_date` date DEFAULT NULL COMMENT 'Date on address proof document',
  `residential_address` text DEFAULT NULL,
  `ocr_data` longtext CHARACTER SET utf8mb4 COLLATE utf8mb4_bin DEFAULT NULL COMMENT 'OCR extracted data from ID document' CHECK (json_valid(`ocr_data`)),
  `ocr_confidence` decimal(5,2) DEFAULT NULL COMMENT 'OCR confidence score 0-100',
  `ocr_status` enum('PENDING','SUCCESS','FAILED','MANUAL_REVIEW') DEFAULT 'PENDING',
  `document_expired` tinyint(1) DEFAULT 0,
  `document_quality_score` decimal(5,2) DEFAULT NULL COMMENT 'Image quality score',
  `admin_remarks` text DEFAULT NULL,
  `reviewed_by` int(10) unsigned DEFAULT NULL,
  `is_encrypted` tinyint(1) DEFAULT 0,
  `encryption_key_id` varchar(100) DEFAULT NULL COMMENT 'Reference to encryption key used',
  `gdpr_consent` tinyint(1) DEFAULT 0,
  `data_retention_date` timestamp NULL DEFAULT NULL COMMENT 'When to delete sensitive data',
  PRIMARY KEY (`id`),
  KEY `kyc_submissions_reviewer_id_foreign` (`reviewer_id`),
  KEY `kyc_submissions_status_index` (`status`),
  KEY `kyc_submissions_user_id_index` (`user_id`),
  KEY `kyc_submissions_submitted_at_index` (`submitted_at`),
  KEY `kyc_submissions_reviewed_by_foreign` (`reviewed_by`),
  KEY `idx_kyc_submissions_reviewer_id` (`reviewer_id`),
  KEY `idx_kyc_submissions_status_created` (`status`,`created_at`),
  CONSTRAINT `kyc_submissions_reviewed_by_foreign` FOREIGN KEY (`reviewed_by`) REFERENCES `users` (`id`),
  CONSTRAINT `kyc_submissions_reviewer_id_foreign` FOREIGN KEY (`reviewer_id`) REFERENCES `users` (`id`) ON DELETE SET NULL,
  CONSTRAINT `kyc_submissions_user_id_foreign` FOREIGN KEY (`user_id`) REFERENCES `users` (`id`) ON DELETE CASCADE
) ENGINE=InnoDB AUTO_INCREMENT=7 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;

-- --------------------------------------------------------

--
-- Table structure for table `newsletter_campaigns`
--

DROP TABLE IF EXISTS `newsletter_campaigns`;
CREATE TABLE `newsletter_campaigns` (
  `id` int(10) unsigned NOT NULL AUTO_INCREMENT,
  `subject` varchar(255) NOT NULL,
  `content` text NOT NULL,
  `plain_text` text DEFAULT NULL,
  `status` enum('DRAFT','SCHEDULED','SENDING','SENT','FAILED') DEFAULT 'DRAFT',
  `admin_id` int(10) unsigned DEFAULT NULL,
  `scheduled_at` timestamp NULL DEFAULT NULL,
  `sent_at` timestamp NULL DEFAULT NULL,
  `total_recipients` int(11) DEFAULT 0,
  `sent_count` int(11) DEFAULT 0,
  `failed_count` int(11) DEFAULT 0,
  `created_at` timestamp NOT NULL DEFAULT current_timestamp(),
  `updated_at` timestamp NOT NULL DEFAULT current_timestamp(),
  PRIMARY KEY (`id`),
  KEY `newsletter_campaigns_admin_id_foreign` (`admin_id`),
  KEY `newsletter_campaigns_status_index` (`status`),
  KEY `newsletter_campaigns_scheduled_at_index` (`scheduled_at`),
  CONSTRAINT `newsletter_campaigns_admin_id_foreign` FOREIGN KEY (`admin_id`) REFERENCES `users` (`id`) ON DELETE SET NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;

-- --------------------------------------------------------

--
-- Table structure for table `newsletter_logs`
--

DROP TABLE IF EXISTS `newsletter_logs`;
CREATE TABLE `newsletter_logs` (
  `id` int(10) unsigned NOT NULL AUTO_INCREMENT,
  `campaign_id` int(10) unsigned NOT NULL,
  `subscriber_id` int(10) unsigned DEFAULT NULL,
  `email` varchar(255) NOT NULL,
  `status` enum('SENT','FAILED','BOUNCED') NOT NULL,
  `error_message` text DEFAULT NULL,
  `sent_at` timestamp NOT NULL DEFAULT current_timestamp(),
  PRIMARY KEY (`id`),
  KEY `newsletter_logs_campaign_id_index` (`campaign_id`),
  KEY `newsletter_logs_subscriber_id_index` (`subscriber_id`),
  CONSTRAINT `newsletter_logs_campaign_id_foreign` FOREIGN KEY (`campaign_id`) REFERENCES `newsletter_campaigns` (`id`) ON DELETE CASCADE,
  CONSTRAINT `newsletter_logs_subscriber_id_foreign` FOREIGN KEY (`subscriber_id`) REFERENCES `newsletter_subscribers` (`id`) ON DELETE SET NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;

-- --------------------------------------------------------

--
-- Table structure for table `newsletter_subscribers`
--

DROP TABLE IF EXISTS `newsletter_subscribers`;
CREATE TABLE `newsletter_subscribers` (
  `id` int(10) unsigned NOT NULL AUTO_INCREMENT,
  `email` varchar(255) NOT NULL,
  `name` varchar(255) DEFAULT NULL,
  `status` enum('ACTIVE','UNSUBSCRIBED','BOUNCED') DEFAULT 'ACTIVE',
  `subscription_token` varchar(64) DEFAULT NULL,
  `source` varchar(50) DEFAULT NULL COMMENT 'Where they subscribed from',
  `subscribed_at` timestamp NOT NULL DEFAULT current_timestamp(),
  `unsubscribed_at` timestamp NULL DEFAULT NULL,
  `created_at` timestamp NOT NULL DEFAULT current_timestamp(),
  `updated_at` timestamp NOT NULL DEFAULT current_timestamp(),
  PRIMARY KEY (`id`),
  UNIQUE KEY `newsletter_subscribers_email_unique` (`email`),
  UNIQUE KEY `newsletter_subscribers_subscription_token_unique` (`subscription_token`),
  KEY `newsletter_subscribers_email_index` (`email`),
  KEY `newsletter_subscribers_status_index` (`status`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;

-- --------------------------------------------------------

--
-- Table structure for table `notifications`
--

DROP TABLE IF EXISTS `notifications`;
CREATE TABLE `notifications` (
  `id` int(10) unsigned NOT NULL AUTO_INCREMENT,
  `title` varchar(255) NOT NULL,
  `body` text NOT NULL,
  `audience` enum('ALL','USER') NOT NULL DEFAULT 'ALL',
  `user_id` int(10) unsigned DEFAULT NULL,
  `url` varchar(255) DEFAULT NULL,
  `created_at` timestamp NOT NULL DEFAULT current_timestamp(),
  PRIMARY KEY (`id`),
  KEY `notifications_user_id_index` (`user_id`),
  KEY `notifications_audience_user_id_index` (`audience`,`user_id`),
  KEY `notifications_created_at_index` (`created_at`),
  KEY `idx_notifications_audience_user_created` (`audience`,`user_id`,`created_at`),
  KEY `idx_notifications_user_created` (`user_id`,`created_at`),
  CONSTRAINT `notifications_user_id_foreign` FOREIGN KEY (`user_id`) REFERENCES `users` (`id`) ON DELETE CASCADE
) ENGINE=InnoDB AUTO_INCREMENT=10 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;

-- --------------------------------------------------------

--
-- Table structure for table `notification_hides`
--

DROP TABLE IF EXISTS `notification_hides`;
CREATE TABLE `notification_hides` (
  `id` int(10) unsigned NOT NULL AUTO_INCREMENT,
  `notification_id` int(10) unsigned NOT NULL,
  `user_id` int(10) unsigned NOT NULL,
  `hidden_at` timestamp NOT NULL DEFAULT current_timestamp(),
  PRIMARY KEY (`id`),
  UNIQUE KEY `notification_hides_notification_id_user_id_unique` (`notification_id`,`user_id`),
  KEY `notification_hides_notification_id_index` (`notification_id`),
  KEY `notification_hides_user_id_index` (`user_id`),
  CONSTRAINT `notification_hides_notification_id_foreign` FOREIGN KEY (`notification_id`) REFERENCES `notifications` (`id`) ON DELETE CASCADE,
  CONSTRAINT `notification_hides_user_id_foreign` FOREIGN KEY (`user_id`) REFERENCES `users` (`id`) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;

-- --------------------------------------------------------

--
-- Table structure for table `notification_reads`
--

DROP TABLE IF EXISTS `notification_reads`;
CREATE TABLE `notification_reads` (
  `id` int(10) unsigned NOT NULL AUTO_INCREMENT,
  `notification_id` int(10) unsigned NOT NULL,
  `user_id` int(10) unsigned NOT NULL,
  `read_at` timestamp NOT NULL DEFAULT current_timestamp(),
  PRIMARY KEY (`id`),
  UNIQUE KEY `notification_reads_notification_id_user_id_unique` (`notification_id`,`user_id`),
  KEY `notification_reads_notification_id_index` (`notification_id`),
  KEY `notification_reads_user_id_index` (`user_id`),
  KEY `idx_notification_reads_user_read` (`user_id`,`read_at`),
  CONSTRAINT `notification_reads_notification_id_foreign` FOREIGN KEY (`notification_id`) REFERENCES `notifications` (`id`) ON DELETE CASCADE,
  CONSTRAINT `notification_reads_user_id_foreign` FOREIGN KEY (`user_id`) REFERENCES `users` (`id`) ON DELETE CASCADE
) ENGINE=InnoDB AUTO_INCREMENT=22 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;

-- --------------------------------------------------------

--
-- Table structure for table `notification_read_events`
--

DROP TABLE IF EXISTS `notification_read_events`;
CREATE TABLE `notification_read_events` (
  `id` int(10) unsigned NOT NULL AUTO_INCREMENT,
  `user_id` int(10) unsigned NOT NULL,
  `notification_id` int(10) unsigned NOT NULL,
  `created_at` timestamp NOT NULL DEFAULT current_timestamp(),
  PRIMARY KEY (`id`),
  KEY `notification_read_events_user_id_index` (`user_id`),
  KEY `notification_read_events_notification_id_index` (`notification_id`),
  KEY `notification_read_events_created_at_index` (`created_at`),
  CONSTRAINT `notification_read_events_notification_id_foreign` FOREIGN KEY (`notification_id`) REFERENCES `notifications` (`id`) ON DELETE CASCADE,
  CONSTRAINT `notification_read_events_user_id_foreign` FOREIGN KEY (`user_id`) REFERENCES `users` (`id`) ON DELETE CASCADE
) ENGINE=InnoDB AUTO_INCREMENT=2 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;

-- --------------------------------------------------------

--
-- Table structure for table `orders`
--

DROP TABLE IF EXISTS `orders`;
CREATE TABLE `orders` (
  `id` int(10) unsigned NOT NULL AUTO_INCREMENT,
  `user_id` int(10) unsigned NOT NULL,
  `status` varchar(255) NOT NULL DEFAULT 'PENDING',
  `total_amount` decimal(12,2) NOT NULL DEFAULT 0.00,
  `created_at` timestamp NOT NULL DEFAULT current_timestamp(),
  `updated_at` timestamp NOT NULL DEFAULT current_timestamp(),
  PRIMARY KEY (`id`),
  KEY `orders_user_id_foreign` (`user_id`),
  KEY `idx_orders_user_id` (`user_id`),
  KEY `idx_orders_status` (`status`),
  KEY `idx_orders_created_at` (`created_at`),
  CONSTRAINT `orders_user_id_foreign` FOREIGN KEY (`user_id`) REFERENCES `users` (`id`) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;

-- --------------------------------------------------------

--
-- Table structure for table `order_items`
--

DROP TABLE IF EXISTS `order_items`;
CREATE TABLE `order_items` (
  `id` int(10) unsigned NOT NULL AUTO_INCREMENT,
  `order_id` int(10) unsigned NOT NULL,
  `product_id` int(10) unsigned NOT NULL,
  `quantity` int(10) unsigned NOT NULL DEFAULT 1,
  `unit_price` decimal(12,2) NOT NULL DEFAULT 0.00,
  `created_at` timestamp NOT NULL DEFAULT current_timestamp(),
  `updated_at` timestamp NOT NULL DEFAULT current_timestamp(),
  PRIMARY KEY (`id`),
  KEY `order_items_order_id_foreign` (`order_id`),
  KEY `order_items_product_id_foreign` (`product_id`),
  CONSTRAINT `order_items_order_id_foreign` FOREIGN KEY (`order_id`) REFERENCES `orders` (`id`) ON DELETE CASCADE,
  CONSTRAINT `order_items_product_id_foreign` FOREIGN KEY (`product_id`) REFERENCES `products` (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;

-- --------------------------------------------------------

--
-- Table structure for table `pending_registrations`
--

DROP TABLE IF EXISTS `pending_registrations`;
CREATE TABLE `pending_registrations` (
  `id` int(10) unsigned NOT NULL AUTO_INCREMENT,
  `name` varchar(255) NOT NULL,
  `email` varchar(255) NOT NULL,
  `password_hash` varchar(255) NOT NULL,
  `phone` varchar(255) DEFAULT NULL,
  `address` varchar(255) DEFAULT NULL,
  `dob` date NOT NULL,
  `gender` enum('MALE','FEMALE','PREFER_NOT_TO_SAY') DEFAULT NULL,
  `token` varchar(255) NOT NULL,
  `expires_at` datetime NOT NULL,
  `created_at` timestamp NOT NULL DEFAULT current_timestamp(),
  `updated_at` timestamp NOT NULL DEFAULT current_timestamp(),
  `referral_code` varchar(20) DEFAULT NULL COMMENT 'Referral code used during registration',
  PRIMARY KEY (`id`),
  UNIQUE KEY `pending_registrations_token_unique` (`token`),
  KEY `pending_registrations_email_index` (`email`),
  KEY `pending_registrations_token_index` (`token`),
  KEY `pending_registrations_expires_at_index` (`expires_at`),
  KEY `pending_registrations_gender_index` (`gender`)
) ENGINE=InnoDB AUTO_INCREMENT=13 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;

-- --------------------------------------------------------

--
-- Table structure for table `platform_settings`
--

DROP TABLE IF EXISTS `platform_settings`;
CREATE TABLE `platform_settings` (
  `id` int(10) unsigned NOT NULL AUTO_INCREMENT,
  `setting_key` varchar(100) NOT NULL,
  `setting_value` text DEFAULT NULL,
  `is_encrypted` tinyint(1) DEFAULT 0,
  `category` varchar(50) DEFAULT NULL,
  `description` text DEFAULT NULL,
  `updated_at` timestamp NOT NULL DEFAULT current_timestamp(),
  `created_at` timestamp NOT NULL DEFAULT current_timestamp(),
  PRIMARY KEY (`id`),
  UNIQUE KEY `platform_settings_setting_key_unique` (`setting_key`),
  KEY `platform_settings_setting_key_index` (`setting_key`),
  KEY `platform_settings_category_index` (`category`)
) ENGINE=InnoDB AUTO_INCREMENT=4 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;

-- --------------------------------------------------------

--
-- Table structure for table `posts`
--

DROP TABLE IF EXISTS `posts`;
CREATE TABLE `posts` (
  `id` int(10) unsigned NOT NULL AUTO_INCREMENT,
  `title` varchar(255) NOT NULL,
  `slug` varchar(255) NOT NULL,
  `category` varchar(80) DEFAULT NULL,
  `excerpt` text DEFAULT NULL,
  `content` text NOT NULL,
  `require_login` tinyint(1) NOT NULL DEFAULT 0,
  `status` enum('DRAFT','PUBLISHED') NOT NULL DEFAULT 'DRAFT',
  `author_id` int(10) unsigned DEFAULT NULL,
  `published_at` timestamp NOT NULL DEFAULT current_timestamp() ON UPDATE current_timestamp(),
  `created_at` timestamp NOT NULL DEFAULT current_timestamp(),
  `updated_at` timestamp NOT NULL DEFAULT current_timestamp(),
  `cover_image` varchar(255) DEFAULT NULL,
  `reading_minutes` int(10) unsigned DEFAULT NULL,
  `view_count` int(10) unsigned NOT NULL DEFAULT 0,
  `seo_title` varchar(255) DEFAULT NULL,
  `seo_description` varchar(300) DEFAULT NULL,
  PRIMARY KEY (`id`),
  UNIQUE KEY `posts_slug_unique` (`slug`),
  KEY `posts_status_published_at_index` (`status`,`published_at`),
  KEY `posts_category_index` (`category`),
  KEY `posts_published_at_index` (`published_at`),
  KEY `posts_view_count_index` (`view_count`),
  KEY `idx_posts_slug` (`slug`),
  KEY `idx_posts_published_at` (`published_at`),
  KEY `idx_posts_category` (`category`)
) ENGINE=InnoDB AUTO_INCREMENT=3 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;

-- --------------------------------------------------------

--
-- Table structure for table `post_tags`
--

DROP TABLE IF EXISTS `post_tags`;
CREATE TABLE `post_tags` (
  `id` int(10) unsigned NOT NULL AUTO_INCREMENT,
  `post_id` int(10) unsigned NOT NULL,
  `tag_id` int(10) unsigned NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE KEY `post_tags_post_id_tag_id_unique` (`post_id`,`tag_id`),
  KEY `post_tags_tag_id_index` (`tag_id`),
  CONSTRAINT `post_tags_post_id_foreign` FOREIGN KEY (`post_id`) REFERENCES `posts` (`id`) ON DELETE CASCADE,
  CONSTRAINT `post_tags_tag_id_foreign` FOREIGN KEY (`tag_id`) REFERENCES `tags` (`id`) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;

-- --------------------------------------------------------

--
-- Table structure for table `products`
--

DROP TABLE IF EXISTS `products`;
CREATE TABLE `products` (
  `id` int(10) unsigned NOT NULL AUTO_INCREMENT,
  `title` varchar(255) NOT NULL,
  `description` text DEFAULT NULL,
  `moq` int(11) NOT NULL DEFAULT 1,
  `price_per_unit` decimal(12,2) NOT NULL,
  `stock_status` enum('IN_STOCK','OUT_OF_STOCK','PREORDER') NOT NULL DEFAULT 'IN_STOCK',
  `category_id` int(10) unsigned DEFAULT NULL,
  `images` longtext CHARACTER SET utf8mb4 COLLATE utf8mb4_bin DEFAULT NULL CHECK (json_valid(`images`)),
  `videos` longtext CHARACTER SET utf8mb4 COLLATE utf8mb4_bin DEFAULT NULL CHECK (json_valid(`videos`)),
  `active` tinyint(1) NOT NULL DEFAULT 1,
  `created_at` timestamp NOT NULL DEFAULT current_timestamp(),
  `updated_at` timestamp NOT NULL DEFAULT current_timestamp(),
  PRIMARY KEY (`id`),
  KEY `idx_products_category` (`category_id`),
  KEY `idx_products_created_at` (`created_at`),
  CONSTRAINT `products_category_id_foreign` FOREIGN KEY (`category_id`) REFERENCES `categories` (`id`) ON DELETE SET NULL
) ENGINE=InnoDB AUTO_INCREMENT=4 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;

-- --------------------------------------------------------

--
-- Table structure for table `quotations`
--

DROP TABLE IF EXISTS `quotations`;
CREATE TABLE `quotations` (
  `id` int(10) unsigned NOT NULL AUTO_INCREMENT,
  `reference` varchar(255) NOT NULL,
  `user_id` int(10) unsigned NOT NULL,
  `status` enum('REQUESTED','REPLIED','PAID','CANCELLED') NOT NULL DEFAULT 'REQUESTED',
  `subtotal_amount` decimal(12,2) NOT NULL DEFAULT 0.00,
  `logistics_amount` decimal(12,2) NOT NULL DEFAULT 0.00,
  `discount_amount` decimal(12,2) NOT NULL DEFAULT 0.00,
  `total_amount` decimal(12,2) NOT NULL DEFAULT 0.00,
  `currency` varchar(8) NOT NULL DEFAULT 'USD',
  `allowed_payment_methods` varchar(120) DEFAULT NULL,
  `notes_user` text DEFAULT NULL,
  `notes_admin` text DEFAULT NULL,
  `replied_at` datetime DEFAULT NULL,
  `paid_at` datetime DEFAULT NULL,
  `created_at` timestamp NOT NULL DEFAULT current_timestamp(),
  `updated_at` timestamp NOT NULL DEFAULT current_timestamp(),
  PRIMARY KEY (`id`),
  UNIQUE KEY `quotations_reference_unique` (`reference`),
  KEY `quotations_user_id_status_index` (`user_id`,`status`),
  KEY `idx_quotations_user_id` (`user_id`),
  KEY `idx_quotations_status` (`status`),
  KEY `idx_quotations_created_at` (`created_at`),
  KEY `idx_quotations_status_user` (`status`,`user_id`),
  CONSTRAINT `quotations_user_id_foreign` FOREIGN KEY (`user_id`) REFERENCES `users` (`id`) ON DELETE CASCADE
) ENGINE=InnoDB AUTO_INCREMENT=8 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;

-- --------------------------------------------------------

--
-- Table structure for table `quotation_items`
--

DROP TABLE IF EXISTS `quotation_items`;
CREATE TABLE `quotation_items` (
  `id` int(10) unsigned NOT NULL AUTO_INCREMENT,
  `quotation_id` int(10) unsigned NOT NULL,
  `product_id` int(10) unsigned NOT NULL,
  `product_name` varchar(255) NOT NULL,
  `quantity` int(10) unsigned NOT NULL DEFAULT 1,
  `unit_price` decimal(12,2) NOT NULL DEFAULT 0.00,
  `line_total` decimal(12,2) NOT NULL DEFAULT 0.00,
  `created_at` timestamp NOT NULL DEFAULT current_timestamp(),
  `updated_at` timestamp NOT NULL DEFAULT current_timestamp(),
  PRIMARY KEY (`id`),
  KEY `quotation_items_product_id_foreign` (`product_id`),
  KEY `quotation_items_quotation_id_index` (`quotation_id`),
  CONSTRAINT `quotation_items_product_id_foreign` FOREIGN KEY (`product_id`) REFERENCES `products` (`id`),
  CONSTRAINT `quotation_items_quotation_id_foreign` FOREIGN KEY (`quotation_id`) REFERENCES `quotations` (`id`) ON DELETE CASCADE
) ENGINE=InnoDB AUTO_INCREMENT=10 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;

-- --------------------------------------------------------

--
-- Table structure for table `risk_events`
--

DROP TABLE IF EXISTS `risk_events`;
CREATE TABLE `risk_events` (
  `id` int(10) unsigned NOT NULL AUTO_INCREMENT,
  `user_id` int(10) unsigned NOT NULL,
  `event_type` varchar(255) NOT NULL,
  `delta` int(11) NOT NULL DEFAULT 0,
  `resulting_score` int(11) NOT NULL DEFAULT 0,
  `resulting_level` enum('LOW','MEDIUM','HIGH','CRITICAL') NOT NULL DEFAULT 'LOW',
  `metadata` text DEFAULT NULL,
  `created_at` timestamp NOT NULL DEFAULT current_timestamp(),
  PRIMARY KEY (`id`),
  KEY `risk_events_user_id_index` (`user_id`),
  KEY `risk_events_event_type_index` (`event_type`),
  KEY `risk_events_created_at_index` (`created_at`),
  KEY `idx_risk_events_user_created` (`user_id`,`created_at`),
  CONSTRAINT `risk_events_user_id_foreign` FOREIGN KEY (`user_id`) REFERENCES `users` (`id`) ON DELETE CASCADE
) ENGINE=InnoDB AUTO_INCREMENT=2 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;

-- --------------------------------------------------------

--
-- Table structure for table `tags`
--

DROP TABLE IF EXISTS `tags`;
CREATE TABLE `tags` (
  `id` int(10) unsigned NOT NULL AUTO_INCREMENT,
  `name` varchar(60) NOT NULL,
  `created_at` timestamp NOT NULL DEFAULT current_timestamp(),
  `updated_at` timestamp NOT NULL DEFAULT current_timestamp(),
  PRIMARY KEY (`id`),
  UNIQUE KEY `tags_name_unique` (`name`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;

-- --------------------------------------------------------

--
-- Table structure for table `tokens`
--

DROP TABLE IF EXISTS `tokens`;
CREATE TABLE `tokens` (
  `id` int(10) unsigned NOT NULL AUTO_INCREMENT,
  `user_id` int(10) unsigned NOT NULL,
  `type` varchar(255) NOT NULL,
  `token` varchar(255) NOT NULL,
  `expires_at` datetime NOT NULL,
  `created_at` timestamp NOT NULL DEFAULT current_timestamp(),
  `updated_at` timestamp NOT NULL DEFAULT current_timestamp(),
  PRIMARY KEY (`id`),
  UNIQUE KEY `tokens_token_unique` (`token`),
  KEY `tokens_user_id_foreign` (`user_id`),
  CONSTRAINT `tokens_user_id_foreign` FOREIGN KEY (`user_id`) REFERENCES `users` (`id`) ON DELETE CASCADE
) ENGINE=InnoDB AUTO_INCREMENT=5 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;

-- --------------------------------------------------------

--
-- Table structure for table `twofa_recovery_codes`
--

DROP TABLE IF EXISTS `twofa_recovery_codes`;
CREATE TABLE `twofa_recovery_codes` (
  `id` int(10) unsigned NOT NULL AUTO_INCREMENT,
  `user_id` int(10) unsigned NOT NULL,
  `code_hash` varchar(255) NOT NULL,
  `used` tinyint(1) NOT NULL DEFAULT 0,
  `used_at` timestamp NULL DEFAULT NULL,
  `created_at` timestamp NOT NULL DEFAULT current_timestamp(),
  `updated_at` timestamp NOT NULL DEFAULT current_timestamp(),
  PRIMARY KEY (`id`),
  KEY `twofa_recovery_codes_user_id_used_index` (`user_id`,`used`),
  CONSTRAINT `twofa_recovery_codes_user_id_foreign` FOREIGN KEY (`user_id`) REFERENCES `users` (`id`) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;

-- --------------------------------------------------------

--
-- Table structure for table `users`
--

DROP TABLE IF EXISTS `users`;
CREATE TABLE `users` (
  `id` int(10) unsigned NOT NULL AUTO_INCREMENT,
  `name` varchar(255) NOT NULL,
  `email` varchar(255) NOT NULL,
  `password_hash` varchar(255) NOT NULL,
  `token_version` int(11) NOT NULL DEFAULT 1,
  `phone` varchar(255) DEFAULT NULL,
  `address` varchar(255) DEFAULT NULL,
  `dob` date DEFAULT NULL,
  `gender` enum('MALE','FEMALE','PREFER_NOT_TO_SAY') DEFAULT NULL,
  `role` enum('ADMIN','CUSTOMER') NOT NULL DEFAULT 'CUSTOMER',
  `email_verified` tinyint(1) NOT NULL DEFAULT 0,
  `is_active` tinyint(1) NOT NULL DEFAULT 1,
  `twofa_secret` varchar(255) DEFAULT NULL,
  `email_2fa_enabled` tinyint(1) DEFAULT 0,
  `email_2fa_method` varchar(20) DEFAULT NULL COMMENT 'totp or email',
  `avatar_url` varchar(255) DEFAULT NULL,
  `created_at` timestamp NOT NULL DEFAULT current_timestamp(),
  `updated_at` timestamp NOT NULL DEFAULT current_timestamp(),
  `deleted_at` datetime DEFAULT NULL,
  `referral_code` varchar(20) DEFAULT NULL COMMENT 'Affiliate referral code that referred this user',
  PRIMARY KEY (`id`),
  UNIQUE KEY `users_email_unique` (`email`),
  KEY `idx_users_email` (`email`),
  KEY `idx_users_name` (`name`),
  KEY `idx_users_is_active` (`is_active`),
  KEY `users_referral_code_index` (`referral_code`)
) ENGINE=InnoDB AUTO_INCREMENT=12 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;

-- --------------------------------------------------------

--
-- Table structure for table `user_verification_state`
--

DROP TABLE IF EXISTS `user_verification_state`;
CREATE TABLE `user_verification_state` (
  `id` int(10) unsigned NOT NULL AUTO_INCREMENT,
  `user_id` int(10) unsigned NOT NULL,
  `status` enum('UNVERIFIED','BASIC_PENDING','BASIC_VERIFIED','KYC_PENDING','KYC_VERIFIED','REJECTED','LOCKED') NOT NULL DEFAULT 'UNVERIFIED',
  `risk_score` int(11) NOT NULL DEFAULT 0,
  `risk_level` enum('LOW','MEDIUM','HIGH','CRITICAL') NOT NULL DEFAULT 'LOW',
  `manual_lock` tinyint(1) NOT NULL DEFAULT 0,
  `lock_reason` text DEFAULT NULL,
  `locked_at` timestamp NULL DEFAULT NULL,
  `basic_verified_at` timestamp NULL DEFAULT NULL,
  `kyc_submission_id` int(10) unsigned DEFAULT NULL,
  `kyc_verified_at` timestamp NULL DEFAULT NULL,
  `created_at` timestamp NOT NULL DEFAULT current_timestamp(),
  `updated_at` timestamp NOT NULL DEFAULT current_timestamp(),
  PRIMARY KEY (`id`),
  UNIQUE KEY `user_verification_state_user_id_unique` (`user_id`),
  KEY `user_verification_state_kyc_submission_id_foreign` (`kyc_submission_id`),
  KEY `user_verification_state_status_index` (`status`),
  KEY `user_verification_state_risk_level_index` (`risk_level`),
  KEY `user_verification_state_risk_score_index` (`risk_score`),
  KEY `user_verification_state_user_id_index` (`user_id`),
  KEY `idx_verification_state_status` (`status`),
  KEY `idx_verification_state_risk_level` (`risk_level`),
  CONSTRAINT `user_verification_state_kyc_submission_id_foreign` FOREIGN KEY (`kyc_submission_id`) REFERENCES `kyc_submissions` (`id`) ON DELETE SET NULL,
  CONSTRAINT `user_verification_state_user_id_foreign` FOREIGN KEY (`user_id`) REFERENCES `users` (`id`) ON DELETE CASCADE
) ENGINE=InnoDB AUTO_INCREMENT=2 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;

-- --------------------------------------------------------

--
-- Table structure for table `verification_state_events`
--

DROP TABLE IF EXISTS `verification_state_events`;
CREATE TABLE `verification_state_events` (
  `id` int(10) unsigned NOT NULL AUTO_INCREMENT,
  `user_id` int(10) unsigned NOT NULL,
  `from_status` varchar(255) NOT NULL,
  `to_status` varchar(255) NOT NULL,
  `actor_id` int(10) unsigned DEFAULT NULL,
  `metadata` text DEFAULT NULL,
  `created_at` timestamp NOT NULL DEFAULT current_timestamp(),
  PRIMARY KEY (`id`),
  KEY `verification_state_events_actor_id_foreign` (`actor_id`),
  KEY `verification_state_events_user_id_created_at_index` (`user_id`,`created_at`),
  KEY `verification_state_events_to_status_index` (`to_status`),
  CONSTRAINT `verification_state_events_actor_id_foreign` FOREIGN KEY (`actor_id`) REFERENCES `users` (`id`) ON DELETE SET NULL,
  CONSTRAINT `verification_state_events_user_id_foreign` FOREIGN KEY (`user_id`) REFERENCES `users` (`id`) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;

-- --------------------------------------------------------

COMMIT;

/*!40101 SET CHARACTER_SET_CLIENT=@OLD_CHARACTER_SET_CLIENT */;
/*!40101 SET CHARACTER_SET_RESULTS=@OLD_CHARACTER_SET_RESULTS */;
/*!40101 SET COLLATION_CONNECTION=@OLD_COLLATION_CONNECTION */;
