/**
 * Export Database Schema Script
 * Generates SQL dump files for keohams and keohams_public_blog databases
 */

const db = require('../src/config/db');
const publicDb = require('../src/config/publicDb');
const fs = require('fs');
const path = require('path');

async function exportDatabase() {
  console.log('Starting database export...\n');
  
  try {
    // Get all table names from main database
    const mainTables = await db.raw(`
      SELECT TABLE_NAME 
      FROM information_schema.TABLES 
      WHERE TABLE_SCHEMA = 'keohams' 
      AND TABLE_TYPE = 'BASE TABLE'
      ORDER BY TABLE_NAME
    `);
    
    // Get all table names from public blog database
    const publicTables = await publicDb.raw(`
      SELECT TABLE_NAME 
      FROM information_schema.TABLES 
      WHERE TABLE_SCHEMA = 'keohams_public_blog' 
      AND TABLE_TYPE = 'BASE TABLE'
      ORDER BY TABLE_NAME
    `);
    
    console.log(`Found ${mainTables[0].length} tables in keohams database`);
    console.log(`Found ${publicTables[0].length} tables in keohams_public_blog database`);
    
    // Generate main database SQL
    let mainSql = generateHeader('keohams');
    
    for (const table of mainTables[0]) {
      const tableName = table.TABLE_NAME;
      console.log(`Exporting ${tableName}...`);
      
      // Get CREATE TABLE statement
      const createResult = await db.raw(`SHOW CREATE TABLE \`${tableName}\``);
      const createStatement = createResult[0][0]['Create Table'];
      
      mainSql += `\n-- --------------------------------------------------------\n\n`;
      mainSql += `--\n-- Table structure for table \`${tableName}\`\n--\n\n`;
      mainSql += `DROP TABLE IF EXISTS \`${tableName}\`;\n`;
      mainSql += createStatement + ';\n';
    }
    
    mainSql += generateFooter();
    
    // Generate public blog database SQL
    let publicSql = generateHeader('keohams_public_blog');
    
    for (const table of publicTables[0]) {
      const tableName = table.TABLE_NAME;
      console.log(`Exporting public blog ${tableName}...`);
      
      // Get CREATE TABLE statement
      const createResult = await publicDb.raw(`SHOW CREATE TABLE \`${tableName}\``);
      const createStatement = createResult[0][0]['Create Table'];
      
      publicSql += `\n-- --------------------------------------------------------\n\n`;
      publicSql += `--\n-- Table structure for table \`${tableName}\`\n--\n\n`;
      publicSql += `DROP TABLE IF EXISTS \`${tableName}\`;\n`;
      publicSql += createStatement + ';\n';
    }
    
    publicSql += generateFooter();
    
    // Write to files
    const mainDbPath = path.join(__dirname, '../../keohams.sql');
    const publicDbPath = path.join(__dirname, '../../keohams_public_blog.sql');
    
    fs.writeFileSync(mainDbPath, mainSql, 'utf8');
    fs.writeFileSync(publicDbPath, publicSql, 'utf8');
    
    console.log(`\n✅ Successfully exported databases!`);
    console.log(`📄 Main database: ${mainDbPath}`);
    console.log(`📄 Public blog: ${publicDbPath}`);
    
  } catch (error) {
    console.error('Export error:', error);
    throw error;
  } finally {
    await db.destroy();
    await publicDb.destroy();
  }
}

function generateHeader(databaseName) {
  const now = new Date();
  const dateStr = now.toISOString().slice(0, 19).replace('T', ' ');
  
  return `-- phpMyAdmin SQL Dump
-- Generated by exportDatabases.js
-- Generation Time: ${dateStr}
--
-- Database: \`${databaseName}\`
--

SET SQL_MODE = "NO_AUTO_VALUE_ON_ZERO";
START TRANSACTION;
SET time_zone = "+00:00";

/*!40101 SET @OLD_CHARACTER_SET_CLIENT=@@CHARACTER_SET_CLIENT */;
/*!40101 SET @OLD_CHARACTER_SET_RESULTS=@@CHARACTER_SET_RESULTS */;
/*!40101 SET @OLD_COLLATION_CONNECTION=@@COLLATION_CONNECTION */;
/*!40101 SET NAMES utf8mb4 */;

`;
}

function generateFooter() {
  return `
-- --------------------------------------------------------

COMMIT;

/*!40101 SET CHARACTER_SET_CLIENT=@OLD_CHARACTER_SET_CLIENT */;
/*!40101 SET CHARACTER_SET_RESULTS=@OLD_CHARACTER_SET_RESULTS */;
/*!40101 SET COLLATION_CONNECTION=@OLD_COLLATION_CONNECTION */;
`;
}

// Run the export
exportDatabase()
  .then(() => {
    console.log('\n✨ Database export completed successfully!');
    process.exit(0);
  })
  .catch(error => {
    console.error('\n❌ Database export failed:', error.message);
    process.exit(1);
  });
